# Generated by Django 6.0.1 on 2026-01-12 11:11

import helpdesk_api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', helpdesk_api.models.UserManager()),
            ],
        ),
    ]
