# Generated by Django 6.0.1 on 2026-01-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_api', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='resolved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
