# Generated by Django 6.0.1 on 2026-01-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_api', '0003_issues_resolved_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
