# Generated by Django 6.0.1 on 2026-01-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_api', '0005_remove_user_password_reset_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=6, unique=True),
        ),
    ]
