# Generated by Django 6.0.1 on 2026-01-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_api', '0006_alter_verificationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(db_index=True, editable=False, max_length=6, unique=True),
        ),
    ]
