# Generated by Django 6.0.1 on 2026-03-23 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk_api', '0007_alter_verificationcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
